export { prefixCls, createPrefixCls } from '@test1/core';
export { tokens } from './tokens';
export { getThemeStyles } from './styles';
export { getButtonStyles } from './Button/styles';
export { getPromptStyles } from './Prompt/styles';
export { ThemeProvider, useTheme } from './ThemeContext';
export type { ThemeConfig } from './ThemeContext';
export { Button } from './Button';
export { Prompt } from './Prompt';
export type { ButtonProps } from './Button';
export type { PromptProps } from './Prompt';
